"""``forge init`` — bootstrap a ForgeCLI project.

After ``uv tool install forgecli``, this is the *only* command a user
needs to run.  It:

1. Creates the config / data / cache directories.
2. Writes a starter ``forgecli.toml`` with sensible defaults.
3. Auto-detects API keys that are already in the environment.
4. Runs the ``forge doctor`` self-check.
5. Prints a "Getting Started" guide.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import typer
from rich.panel import Panel
from rich.table import Table

from forgecli import __version__
from forgecli.cli.ui import error, get_console, info, success, warn
from forgecli.utils.paths import ProjectPaths, to_privacy_path

app = typer.Typer(help="Initialize a ForgeCLI project.", no_args_is_help=False)

# The starter config written when no forgecli.toml exists.
_STARTER_CONFIG = """\
# ForgeCLI configuration — generated by `forge init`.
# Docs: https://github.com/mdshzb04/ForgeCli#readme

[app]
log_level = "INFO"

[providers]
default = "{default_provider}"
allowed = {allowed_providers}

[prompt_optimizer]
enabled = true
intensity = "lite"
backend = "ruleset"   # built-in; no external binary needed

[graph]
enabled = true
languages = ["python", "typescript"]

[git]
default_branch = "main"
"""


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    path: str = typer.Option(".", "--path", "-p", help="Project root to initialize."),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite an existing config."),
    json_output: bool = typer.Option(False, "--json", help="Emit JSON instead of a human summary."),
) -> None:
    """Bootstrap a ForgeCLI project: create directories, write config, detect API keys."""
    if ctx.invoked_subcommand is not None:
        return

    console = get_console()
    target = Path(path).resolve()

    # ── 1. Create directories ─────────────────────────────────────────
    paths = ProjectPaths.from_env(cwd=str(target)).ensure()
    dirs_created = [
        ("Config", paths.config_dir),
        ("Data", paths.data_dir),
        ("Cache", paths.cache_dir),
        ("Logs", paths.logs_dir),
        ("Prompts", paths.prompts_dir),
        ("Plugins", paths.plugins_dir),
    ]

    # ── 2. Detect available API keys ──────────────────────────────────
    detected = _detect_providers()
    default_provider = detected[0] if detected else "mock"
    allowed_json = json.dumps(detected if detected else ["mock"])

    # ── 3. Write starter config ───────────────────────────────────────
    config_path = target / "forgecli.toml"
    config_written = False
    if not config_path.exists() or force:
        config_text = _STARTER_CONFIG.format(
            default_provider=default_provider,
            allowed_providers=allowed_json,
        )
        config_path.write_text(config_text, encoding="utf-8")
        config_written = True

    # ── 4. Write .env template (if missing) ───────────────────────────
    env_path = target / ".env"
    env_written = False
    if not env_path.exists():
        env_lines = [
            "# ForgeCLI local environment — generated by `forge init`.",
            "# Add your API keys here or export them in your shell profile.",
            "",
        ]
        for _provider, key_env in _PROVIDER_KEYS:
            value = os.environ.get(key_env, "")
            if value:
                env_lines.append(f"{key_env}={value}")
            else:
                env_lines.append(f"# {key_env}=")
        env_lines.append("")
        env_path.write_text("\n".join(env_lines), encoding="utf-8")
        env_written = True

    # ── 5. Run doctor ─────────────────────────────────────────────────
    doctor_report = _run_doctor_check()

    # ── 6. Output ─────────────────────────────────────────────────────
    if json_output:
        payload: dict[str, Any] = {
            "version": __version__,
            "project_root": str(target),
            "config_path": str(config_path),
            "config_written": config_written,
            "env_written": env_written,
            "detected_providers": detected,
            "default_provider": default_provider,
            "directories": {label: str(p) for label, p in dirs_created},
            "doctor": doctor_report,
        }
        sys.stdout.write(json.dumps(payload, indent=2))
        sys.stdout.write("\n")
        sys.stdout.flush()
        return

    # Human-readable output
    console.print()
    console.print(
        Panel(
            f"[bold cyan]ForgeCLI[/bold cyan] v{__version__}\n"
            f"Project root: [dim]{to_privacy_path(target)}[/dim]",
            title="⚙  forge init",
            border_style="cyan",
            padding=(1, 2),
        )
    )
    console.print()

    # Directories table
    dir_table = Table(title="📁  Directories", show_header=True, header_style="bold")
    dir_table.add_column("Purpose", style="cyan")
    dir_table.add_column("Path", style="dim")
    for label, p in dirs_created:
        dir_table.add_row(label, to_privacy_path(p))
    console.print(dir_table)
    console.print()

    # Config
    if config_written:
        success(f"Wrote config → {to_privacy_path(config_path)}")
    else:
        info(f"Config already exists at {to_privacy_path(config_path)}. Suggest running with [bold cyan]--force[/bold cyan] if you want to overwrite it.")
    if env_written:
        success(f"Wrote .env template → {to_privacy_path(env_path)}")
    console.print()

    # Providers
    if detected:
        provider_str = ", ".join(f"[green]{p}[/green]" for p in detected)
        console.print(f"🔑  Detected API keys: {provider_str}")
        console.print(f"    Default provider: [bold]{default_provider}[/bold]")
    else:
        warn("No API keys detected. ForgeCLI will use the [bold]mock[/bold] provider.")
        console.print("    Set OPENAI_API_KEY, ANTHROPIC_API_KEY, or GOOGLE_API_KEY in your .env")
    console.print()

    # Doctor summary
    _render_doctor_summary(console, doctor_report)
    console.print()

    # Getting started guide
    console.print(
        Panel(
            "[bold]Getting Started[/bold]\n\n"
            "  [cyan]forge --prompt \"Build a REST API for users\"[/cyan]   Run the full pipeline\n"
            "  [cyan]forge build \"Add JWT auth\"[/cyan]                    Build with a prompt\n"
            "  [cyan]forge ask \"How does auth work?\"[/cyan]               Ask about the codebase\n"
            "  [cyan]forge doctor[/cyan]                                  Self-check\n"
            "  [cyan]forge graph build[/cyan]                             Index the repo graph\n\n"
            "[dim]✓ Ponytail prompt optimization is built-in.\n"
            "✓ Graph intelligence is built-in (configure an LLM API key to enable semantic indexing).[/dim]",
            border_style="green",
            padding=(1, 2),
        )
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_PROVIDER_KEYS: list[tuple[str, str]] = [
    ("openai", "OPENAI_API_KEY"),
    ("anthropic", "ANTHROPIC_API_KEY"),
    ("google", "GOOGLE_API_KEY"),
    ("google", "GEMINI_API_KEY"),
]


def _detect_providers() -> list[str]:
    """Return the names of providers whose API key is set in the environment."""
    seen: set[str] = set()
    result: list[str] = []
    for provider, env_var in _PROVIDER_KEYS:
        if provider in seen:
            continue
        if os.environ.get(env_var):
            result.append(provider)
            seen.add(provider)
    return result


def _run_doctor_check() -> dict[str, Any]:
    """Run the doctor dependency check and return a summary dict."""
    try:
        from forgecli.platform import check_dependencies, current_platform, python_version

        platform = current_platform()
        report = check_dependencies()
        return {
            "platform": platform.os.value,
            "python": python_version(),
            "all_ok": len(report.missing_required) == 0,
            "missing_required": [d.name for d in report.missing_required],
            "missing_optional": [
                d.name for d in report.missing if not d.required
            ],
        }
    except Exception as exc:
        return {"error": str(exc), "all_ok": False}


def _render_doctor_summary(console, report: dict[str, Any]) -> None:
    """Print a compact doctor summary."""
    if report.get("error"):
        warn(f"Doctor check failed: {report['error']}")
        return

    if report.get("all_ok"):
        success(
            f"Self-check passed "
            f"(Python {report.get('python', '?')}, "
            f"{report.get('platform', '?')})"
        )
    else:
        missing = report.get("missing_required", [])
        error(f"Missing required dependencies: {', '.join(missing)}")

    optional_missing = report.get("missing_optional", [])
    if optional_missing:
        # Filter out ponytail from "missing" since it's built-in
        optional_missing = [d for d in optional_missing if d != "ponytail"]
        if optional_missing:
            info(f"Optional tools not found: {', '.join(optional_missing)}")


__all__ = ["app"]
